name: CivChat
main: com.untamedears.civchat.CivChat
version: .6
author: Rourke750
commands:
   tell:
      description: Sends a player a message.
      usage: /<command> <player> <message>
      aliases: message, msg, m
   civchat:
      description: Command for loading/saving config.
      usage: /<command> <subcommand>
      permission: civchat.admin
permissions:
   civchat.admin:
      description: Admin commands for civchat.
      default: op
